import { ChatItem } from "@/types";

export const data = {
    searchPlaceholder: 'Search products...',
    welcomeMessage: 'Welcome, Ahmed Auto Parts',
    chartData: [
        { name: 'Jan', sales: 4000 },
        { name: 'Feb', sales: 3000 },
        { name: 'Mar', sales: 5000 },
        { name: 'Apr', sales: 4000 },
        { name: 'May', sales: 6000 },
        { name: 'Jun', sales: 7000 },
    ],
    recentOrders: [
        {
            id: '#AP1234',
            date: '2025-04-20',
            status: 'Shipped',
            items: [
                { productId: 1, productName: 'Brake Pad', quantity: 2, price: 3500 },
                { productId: 2, productName: 'Clip', quantity: 4, price: 200 },
            ],
            customerFirstName: 'Alice',
            customerLastName: 'Johnson',
            email: 'alice@example.com',
            contact: '+923001234567',
            shippingAddress: '123 Main St, Lahore, Pakistan',
            totalAmount: 'PKR 7,400',
        },
        {
            id: '#Al1234',
            date: '2025-04-20',
            status: 'Shipped',
            items: [
                { productId: 3, productName: 'Brake Pad', quantity: 2, price: 3500 },
                { productId: 4, productName: 'Clip', quantity: 4, price: 200 },
            ],
            customerFirstName: 'Alice',
            customerLastName: 'Johnson',
            email: 'alice@example.com',
            contact: '+923001234567',
            shippingAddress: '123 Main St, Lahore, Pakistan',
            totalAmount: 'PKR 7,400',
        },

    ],
    messages: [
        { id: 1, user: 'Customer A', text: 'Is my order #AP1234 shipped?' },
        { id: 2, user: 'Customer B', text: 'I need a discount on bulk orders.' },
    ],
}


export const chatData: ChatItem[] = [
    {
        id: 1,
        name: 'Helen Brooks',
        avatar: '/images/client.jpeg',
        message: 'Hi, seats cover are available and how many colour you have . please send me extra pics.',
        time: '15:56',
        unreadCount: 1,
        isOnline: true,
    },
    {
        id: 2,
        name: 'Kathryn Murphy',
        avatar: '/images/client.jpeg',
        message: 'Hi, seats cover are available and how many colour you have . please send me extra pics.',
        time: 'Wed',
        unreadCount: 2,
        isOnline: true,
    },
    {
        id: 3,
        name: 'James Grey',
        avatar: '/images/client.jpeg',
        message: 'Hi, seats cover are available and how many colour you have . please send me extra pics.',
        time: 'Tue',
        isOnline: false,
    },
    {
        id: 4,
        name: 'Jim Brown',
        avatar: '/images/client.jpeg',
        message: 'Hi, a cover are available and how many colour you have . please send…',
        time: 'Tue',
        isOnline: false,
    },
    {
        id: 5,
        name: 'Helen Brooks',
        avatar: '/images/client.jpeg',
        message: 'Hi, seats cover are available and how many colour you have . please send me extra pics.',
        time: '15:56',
        unreadCount: 1,
        isOnline: true,
    },
    {
        id: 6,
        name: 'Kathryn Murphy',
        avatar: '/images/client.jpeg',
        message: 'Hi, seats cover are available and how many colour you have . please send me extra pics.',
        time: 'Wed',
        unreadCount: 2,
        isOnline: true,
    },
    {
        id: 7,
        name: 'James Grey',
        avatar: '/images/client.jpeg',
        message: 'Hi, seats cover are available and how many colour you have . please send me extra pics.',
        time: 'Tue',
        isOnline: false,
    },
    {
        id: 8,
        name: 'Jim Brown',
        avatar: '/images/client.jpeg',
        message: 'Hi, a cover are available and how many colour you have . please send…',
        time: 'Tue',
        isOnline: false,
    },
]

export const OrderRequest = [
    {
        id: 'REQ-1001',
        customerName: 'Alice Johnson',
        partName: 'Front Brake Pads',
        quantity: 2,
        date: '2025-04-22',
        status: 'Pending',
    },
    {
        id: 'REQ-1002',
        customerName: 'Bob Martinez',
        partName: 'Air Filter',
        quantity: 1,
        date: '2025-04-21',
        status: 'In Progress',
    },
    {
        id: 'REQ-1003',
        customerName: 'Charlie Kim',
        partName: 'Headlight Assembly',
        quantity: 4,
        date: '2025-04-20',
        status: 'Completed',
    },
    {
        id: 'REQ-1004',
        customerName: 'Diana Smith',
        partName: 'Oil Pump',
        quantity: 1,
        date: '2025-04-19',
        status: 'Pending',
    },
    {
        id: 'REQ-1005',
        customerName: 'Ethan Patel',
        partName: 'Radiator Hose',
        quantity: 3,
        date: '2025-04-18',
        status: 'In Progress',
    },
    {
        id: 'REQ-1006',
        customerName: 'Alice Johnson',
        partName: 'Front Brake Pads',
        quantity: 2,
        date: '2025-04-22',
        status: 'Pending',
    },
    {
        id: 'REQ-1007',
        customerName: 'Bob Martinez',
        partName: 'Air Filter',
        quantity: 1,
        date: '2025-04-21',
        status: 'In Progress',
    },
    {
        id: 'REQ-1008',
        customerName: 'Charlie Kim',
        partName: 'Headlight Assembly',
        quantity: 4,
        date: '2025-04-20',
        status: 'Completed',
    },
    {
        id: 'REQ-1009',
        customerName: 'Diana Smith',
        partName: 'Oil Pump',
        quantity: 1,
        date: '2025-04-19',
        status: 'Pending',
    },
    {
        id: 'REQ-1010',
        customerName: 'Ethan Patel',
        partName: 'Radiator Hose',
        quantity: 3,
        date: '2025-04-18',
        status: 'In Progress',
    },
]
export const productList: { id: string; productName: string; date: string; amount: string; status: "Pending" | "Shipped" | "Delivered" | "Cancelled" }[] = [
    {
        id: 'AP-3001',
        productName: 'Brake Pad',
        date: 'April 25, 2025',
        amount: 'PKR 3,500',
        status: 'Pending',
    },
    {
        id: 'AP-3002',
        productName: 'Spark Plug',
        date: 'April 24, 2025',
        amount: 'PKR 1,200',
        status: 'Shipped',
    },
    {
        id: 'AP-3003',
        productName: 'Timing Belt',
        date: 'April 23, 2025',
        amount: 'PKR 4,750',
        status: 'Delivered',
    },
    {
        id: 'AP-3004',
        productName: 'Fuel Pump',
        date: 'April 22, 2025',
        amount: 'PKR 6,800',
        status: 'Cancelled',
    },
    {
        id: 'AP-3005',
        productName: 'Air Filter',
        date: 'April 21, 2025',
        amount: 'PKR 950',
        status: 'Pending',
    },
]
export const reviews = [
    {
        id: 'REV-5001',
        reviewerName: 'Alice Johnson',
        date: 'April 25, 2025',
        productName: 'Brake Pads',
        productImage: "/images/air-filter.jpg",
        rating: 5,
        comment: 'Excellent quality and fast shipping. Exactly as described!',
    },
    {
        id: 'REV-5002',
        reviewerName: 'Bob Smith',
        date: 'April 24, 2025',
        productName: 'Air Filter',
        productImage: "/images/air-filter.jpg",
        rating: 4,
        comment: 'Good product, but packaging could be improved.',
    },
    {
        id: 'REV-5003',
        reviewerName: 'Charlie Kim',
        date: 'April 23, 2025',
        productName: 'Oil Pump',
        productImage: "/images/air-filter.jpg",
        rating: 3,
        comment: 'Works fine but arrived a day late.',
    },
    {
        id: 'REV-5004',
        reviewerName: 'Diana Patel',
        date: 'April 22, 2025',
        productName: 'Headlight Assembly',
        productImage: "/images/air-filter.jpg",
        rating: 5,
        comment: 'Perfect fit and great brightness. Highly recommend!',
    },
    {
        id: 'REV-5005',
        reviewerName: 'Ethan Brown',
        date: 'April 21, 2025',
        productName: 'Fuel Pump',
        productImage: "/images/air-filter.jpg",
        rating: 4,
        comment: 'Installed easily, works as expected.',
    },
];
export const Listedproducts = [
    { id: 1, name: 'Honda City Rims', popularity: 45, sales: 45, color: '#3B82F6' },
    { id: 2, name: 'Collera Lights', popularity: 29, sales: 29, color: '#10B981' },
    { id: 3, name: 'Seats with Cover', popularity: 18, sales: 18, color: '#8B5CF6' },
    { id: 4, name: 'Tyre with wheel', popularity: 25, sales: 25, color: '#F59E0B' },
]

export const SalesData = [
    { date: '2025-04-20', sales: 1200 },
    { date: '2025-04-21', sales: 2100 },
    { date: '2025-04-22', sales: 800 },
    { date: '2025-04-23', sales: 1600 },
    { date: '2025-04-24', sales: 2300 },
    { date: '2025-04-25', sales: 1800 },
    { date: '2025-04-26', sales: 2500 },
]